name = "grad_slingHelmet"
modname = "grad_slingHelmet"
prefix = "grad_slinghelmet"
author = "Gruppe Adler"
files = [
    "mod.cpp",
    "logo_grad_slingHelmet_ca.paa",
    "LICENSE",
    "README.md"
]

key_name = "{{prefix}}-{{version}}"
authority = "{{prefix}}-{{version}}"

releasebuild = [
    "@zip"
]

[header_exts]
version= "{{git \"id 8\"}}"